//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course()
        {
            this.zoom_meeting = new HashSet<zoom_meeting>();
            this.course_subscribe = new HashSet<course_subscribe>();
        }
    
        public int course_id { get; set; }
        public int user_id { get; set; }
        public string course_name { get; set; }
        public string course_desc { get; set; }
        public string course_desc_long { get; set; }
        public int course_length { get; set; }
        public string start_time { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zoom_meeting> zoom_meeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_subscribe> course_subscribe { get; set; }
    }
}
