//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_subscribe
    {
        public int subscribe_id { get; set; }
        public int course_id { get; set; }
        public int user_id { get; set; }
    
        public virtual course course { get; set; }
        public virtual user user { get; set; }
    }
}
