//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<zoom_dev> zoom_dev { get; set; }
        public virtual DbSet<zoom> zooms { get; set; }
        public virtual DbSet<zoom_meeting> zoom_meeting { get; set; }
        public virtual DbSet<zoom_rec> zoom_rec { get; set; }
        public virtual DbSet<course_subscribe> course_subscribe { get; set; }
    }
}
